function Hd = my_bandpass_filter_2
%MY_BANDPASS_FILTER_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 28-May-2024 12:13:25

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 7.2193187187;  % Sampling Frequency

N    = 64;             % Order
Fc1  = 0.83333333333;  % First Cutoff Frequency
Fc2  = 2.5;            % Second Cutoff Frequency
flag = 'scale';        % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
